import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { auth } from "~/server/auth";

import { SetOrganizations } from "~/hooks/useOrganization";
import { SetSession } from "~/hooks/useSession";

import Script from "next/script";
import { AppSidebar } from "~/components/layout/AppSiderbar/AppSidebar";
import { HeaderNav } from "~/components/layout/HeaderNav/HeaderNav";

import { copyScript } from "~/server/types/scripts";
import { getUserOrganizations } from "~/server/db/queries/layout";
import { replaceOnScript } from "~/scripts/get/utils/replaceOnScript";

import type { Organizations } from "~/server/types/InMeasure";

export const metadata: Metadata = {
  title: "InMeasure Analytics",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  const userId = session?.user?.id;
  let organizations: Organizations | null = null;
  if (userId) {
    organizations = await getUserOrganizations(userId);
  }

  const cpyScript = replaceOnScript("a8fab9b1-0bfb-4a61-ad31-6f3a54e15804", "", copyScript);

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="relative flex bg-zinc-950 text-zinc-50">
        <SetSession session={session} />
        <SetOrganizations organizations={organizations} />
        <AppSidebar session={session} />
        <main className="flex w-full flex-col">
          <HeaderNav />
          {children}
        </main>

        <Script
          id="inmeasure-script"
          dangerouslySetInnerHTML={{
            __html: cpyScript,
          }}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
