import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { SetOrganizations } from "~/hooks/useOrganization";
import { auth } from "~/server/auth";
import { getUserOrganizations } from "~/server/db/queries/layout";

import { AppSidebar } from "~/components/layout/AppSiderbar/AppSidebar";
import { HeaderNav } from "~/components/layout/HeaderNav/HeaderNav";

import type { Organizations } from "~/server/types/InMeasure";
import { SetSession } from "~/hooks/useSession";
import Script from "next/script";

export const metadata: Metadata = {
  title: "InMeasure Analytics",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const InMeasureScript = `(function () {
    if (!document.getElementById("im-script")) {
        const element = document.createElement("script");
        element.type = "text/javascript";
        element.async = true;
        element.src = "https://www.inmeasure.com/api/v1/script/test123456789";
        element.id = "im-script";
        const first = document.getElementsByTagName("script")[0];
        first.parentNode.insertBefore(element, first);
    }
})();
`;

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  const userId = session?.user?.id;
  let organizations: Organizations | null = null;
  if (userId) {
    organizations = await getUserOrganizations(userId);
  }

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex h-screen bg-zinc-950 text-white">
        <SetSession session={session} />
        <SetOrganizations organizations={organizations} />
        <AppSidebar session={session} />
        <main className="flex w-full flex-col">
          <HeaderNav />
          {children}
        </main>

        <Script
          id="inmeasure-script"
          dangerouslySetInnerHTML={{
            __html: InMeasureScript,
          }}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
